#!/usr/bin/env python3
"""
Crafty — Company Workspace Initializer
Run this once from the workspace root after cloning crafty/.
Creates config.yaml and the full company/ folder scaffold.

Usage:
    python crafty/scripts/init.py
"""

import os
import sys
from datetime import date

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def ask(prompt: str, default: str = "") -> str:
    if default:
        value = input(f"{prompt} [{default}]: ").strip()
        return value if value else default
    value = input(f"{prompt}: ").strip()
    while not value:
        value = input(f"  (required) {prompt}: ").strip()
    return value


def write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  created  {path}")


def current_quarter() -> str:
    today = date.today()
    q = (today.month - 1) // 3 + 1
    return f"{today.year}-Q{q}"


# ---------------------------------------------------------------------------
# Collect inputs
# ---------------------------------------------------------------------------

def collect_inputs() -> dict:
    print("\n=== Crafty — New Company Workspace Init ===\n")

    company_name = ask("Company name")
    owner        = ask("Your handle (default owner)", default="founder")
    repos_root   = ask("Absolute path to source code repos root (e.g. C:/dev/mycompany-repos)")
    quarter      = ask("Current quarter", default=current_quarter())
    today        = date.today().isoformat()

    return {
        "company_name": company_name,
        "owner":        owner,
        "repos_root":   repos_root,
        "quarter":      quarter,
        "today":        today,
    }


# ---------------------------------------------------------------------------
# File content generators
# ---------------------------------------------------------------------------

def config_yaml(ctx: dict) -> str:
    return f"""\
# Crafty — Workspace Configuration
# Generated by crafty/scripts/init.py — do not commit to the crafty repo.

repos_root: "{ctx['repos_root']}"
default_owner: {ctx['owner']}
company_name: {ctx['company_name']}
"""


def vision_md(ctx: dict) -> str:
    return f"""\
---
type: identity
section: vision
updated_at: {ctx['today']}
---

# Vision

> What the company exists to become — long-term, aspirational, directional.

## Long-Term Vision
<fill>

## Why We Exist
<fill>

## Who We Serve
<fill>
"""


def principles_md(ctx: dict) -> str:
    return f"""\
---
type: identity
section: principles
updated_at: {ctx['today']}
---

# Principles

> Core operating principles that guide decisions. Non-negotiable.

1. <fill>
2. <fill>
3. <fill>
"""


def business_model_md(ctx: dict) -> str:
    return f"""\
---
type: identity
section: business_model
updated_at: {ctx['today']}
---

# Business Model

## Value Proposition
<fill>

## Customer Segments
<fill>

## Revenue Streams
<fill>

## Key Activities
<fill>

## Cost Structure
<fill>
"""


def okr_md(ctx: dict) -> str:
    q = ctx['quarter']
    return f"""\
---
id: O-001
type: objective
title: "[fill]"
status: active
owner: {ctx['owner']}
timeframe: {q}
key_results:
  - KR-001
created_at: {ctx['today']}
updated_at: {ctx['today']}
---

# Objective O-001

## Context

Why this matters...

## Key Results

- **KR-001:** [fill]

## Initiatives

- INIT-001: [fill]
"""


def current_focus_md(ctx: dict) -> str:
    return f"""\
# Current Focus

## Active Quarter

{ctx['quarter']}

## Objective

O-001

## Key Result

KR-001

## Initiative

INIT-001

## Priority Task

[fill — assign once first task is created]

## Notes

[fill — add context about current focus here]
"""


def backlog_md(_ctx: dict) -> str:
    return """\
# Backlog

> Items identified but not yet assigned to an active initiative or sprint.

## Initiatives

- [fill]

## Projects

- [fill]

## Tasks

- [fill]
"""


def decisions_md(ctx: dict) -> str:
    return f"""\
# Decisions

> Key decisions made and the reasoning behind them. Append only — never delete.

| Date | Decision | Rationale | Made By |
|------|----------|-----------|---------|
| {ctx['today']} | Initialized workspace with Crafty framework | Enables agent-driven execution with traceability | {ctx['owner']} |
"""


def decisions_log_md(ctx: dict) -> str:
    return f"""\
# Decisions Log

> All agent and founder decisions. Append only — newest at top.

---

## {ctx['today']}

**Decision:** Initialized company folder structure
**Context:** Following OKR + structured docs methodology via Crafty init script
**Made By:** {ctx['owner']}
**Impact:** Enables agent-driven execution loop

---
"""


def weekly_review_md(ctx: dict) -> str:
    return f"""\
# Weekly Review

> Running log of weekly execution reviews. Append — newest at top.

---

## Week of {ctx['today']}

### Key Result Progress

| KR     | Target | Current | Delta  |
|--------|--------|---------|--------|
| KR-001 | [fill] | [fill]  | [fill] |

### Initiative Status

| Initiative | Status  | Blocker |
|------------|---------|---------|
| INIT-001   | Pending | None    |

### Notes

[fill]
"""


def code_workspace(ctx: dict) -> str:
    name = ctx['company_name'].replace(' ', '')
    return f"""\
{{
  "folders": [
    {{
      "name": "Crafty",
      "path": "./crafty"
    }},
    {{
      "name": "{name}",
      "path": "./company"
    }}
  ],
  "settings": {{}}
}}
"""


def copilot_instructions_md(_ctx: dict) -> str:
    return """\
# Copilot Workspace Instructions

> **Canonical source:** [`crafty/instructions/framework.md`](../crafty/instructions/framework.md)
> This file is the GitHub Copilot injection point. The authoritative framework definition lives in `crafty/`. Update `crafty/instructions/framework.md` first, then reflect changes here.

You are operating inside a workspace governed by the **Crafty** agent framework.

**Before doing any work, read `crafty/instructions/framework.md` in full.**
All rules, folder structure, ID naming, traceability requirements, agent roles, and the execution loop are defined there. No exceptions.

---

## Copilot-Specific Notes

- This file is auto-injected by GitHub Copilot into every chat session.
- The canonical framework rules live in `crafty/instructions/framework.md`. If these two files ever conflict, `framework.md` wins.
- When acting as an agent role (Planner, Operator, Reviewer), also read the corresponding file in `crafty/agents/`.
- Never modify files in `crafty/` without explicit instruction — they are framework, not state.
"""


# ---------------------------------------------------------------------------
# Scaffold
# ---------------------------------------------------------------------------

def scaffold(root: str, ctx: dict) -> None:
    print(f"\nScaffolding workspace at: {root}\n")

    write(os.path.join(root, "crafty", "config.yaml"),                        config_yaml(ctx))
    write(os.path.join(root, "company", "identity", "vision.md"),              vision_md(ctx))
    write(os.path.join(root, "company", "identity", "principles.md"),          principles_md(ctx))
    write(os.path.join(root, "company", "identity", "business_model.md"),      business_model_md(ctx))
    write(os.path.join(root, "company", "strategy", "okr", f"{ctx['quarter']}.md"), okr_md(ctx))
    write(os.path.join(root, "company", "execution", "initiatives", ".gitkeep"), "")
    write(os.path.join(root, "company", "execution", "projects",    ".gitkeep"), "")
    write(os.path.join(root, "company", "execution", "tasks",       ".gitkeep"), "")
    write(os.path.join(root, "company", "state",     "current_focus.md"),      current_focus_md(ctx))
    write(os.path.join(root, "company", "state",     "backlog.md"),            backlog_md(ctx))
    write(os.path.join(root, "company", "state",     "decisions.md"),          decisions_md(ctx))
    write(os.path.join(root, "company", "logs",      "decisions-log.md"),      decisions_log_md(ctx))
    write(os.path.join(root, "company", "logs",      "weekly-review.md"),      weekly_review_md(ctx))
    write(os.path.join(root, "company", ".github",  "copilot-instructions.md"), copilot_instructions_md(ctx))

    workspace_name = ctx['company_name'].replace(' ', '')
    write(os.path.join(root, f"{workspace_name}.code-workspace"),              code_workspace(ctx))

    print(f"""
Done. Next steps:
  1. Fill in company/identity/ files with your vision, principles, and business model.
  2. Define your first OKR in company/strategy/okr/{ctx['quarter']}.md.
  3. Open {workspace_name}.code-workspace in VS Code and start the agent loop.
""")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    # Resolve workspace root: the folder containing crafty/
    script_dir  = os.path.dirname(os.path.abspath(__file__))          # crafty/scripts/
    crafty_dir  = os.path.dirname(script_dir)                         # crafty/
    root        = os.path.dirname(crafty_dir)                         # workspace root

    ctx = collect_inputs()
    scaffold(root, ctx)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nAborted.")
        sys.exit(1)
